# Generated by Django 3.0.6 on 2020-05-31 17:54

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0018_auto_20200530_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to=gallery.models.Gallery.path, verbose_name='Foto')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1, verbose_name='Estado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='revista.Author', verbose_name='Autor')),
            ],
        ),
    ]
