# Generated by Django 3.1.1 on 2020-11-09 22:26

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emprendimiento')),
                ('position', models.IntegerField(verbose_name='Posición')),
                ('url', models.URLField(verbose_name='Link')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Estado')),
                ('image', models.ImageField(upload_to=advertisement.models.Advertisement.path, verbose_name='Image')),
                ('image_mobile', models.ImageField(upload_to=advertisement.models.Advertisement.m_path, verbose_name='Image - Mobile')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
            },
        ),
    ]
