# Generated by Django 3.0.6 on 2020-05-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField(verbose_name='Contenido')),
                ('description', models.TextField(verbose_name='Descripción corta')),
                ('pub_date', models.DateField(verbose_name='Fecha de publicación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Estado')),
                ('claps', models.IntegerField(default=0, verbose_name='Aplausos')),
                ('imagen1', models.ImageField(upload_to='articulos', verbose_name='Imagen principal')),
                ('imagen2', models.ImageField(blank=True, upload_to='articulos', verbose_name='Segunda imagen')),
            ],
            options={
                'ordering': ['-update'],
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('school', models.CharField(max_length=200, verbose_name='Colegio')),
                ('ig_link', models.URLField(blank=True, verbose_name='Instagram Link')),
                ('ig_user', models.CharField(max_length=50, unique=True, verbose_name='Instagram User')),
                ('photo', models.ImageField(upload_to='autores', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='revista.Article', verbose_name='Articulo')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='revista.Authors', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='revista.Category', verbose_name='Categoría'),
        ),
    ]
