# Generated by Django 3.0.6 on 2020-05-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_auto_20200517_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='imagen1',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='imagen2',
            new_name='img2',
        ),
        migrations.AlterField(
            model_name='author',
            name='ig_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instagram User'),
        ),
    ]
