# Generated by Django 3.0.6 on 2020-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_auto_20200517_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='ig_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='img1',
            field=models.ImageField(blank=True, upload_to='articulos', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
