# Generated by Django 3.0.6 on 2020-05-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0004_auto_20200518_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img2',
        ),
        migrations.AddField(
            model_name='article',
            name='imgages',
            field=models.ManyToManyField(blank=True, to='revista.Image'),
        ),
    ]
