# Generated by Django 3.0.6 on 2020-05-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0005_auto_20200519_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imgages',
            new_name='images',
        ),
    ]
