# Generated by Django 3.0.6 on 2020-05-19 20:59

from django.db import migrations, models
import django.db.models.deletion
import revista.models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0006_auto_20200519_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='revista.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='author',
            name='ig_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instagram User (no @)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to=revista.models.Author.path, verbose_name='Foto'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
