# Generated by Django 3.0.6 on 2020-05-19 20:59

from django.db import migrations, models
import django.db.models.deletion
import revista.models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0007_auto_20200519_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=revista.models.Image.path)),
                ('source', models.URLField(verbose_name='Fuente')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='revista.Article', verbose_name='Articulo')),
            ],
        ),
    ]
