# Generated by Django 3.0.6 on 2020-05-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template_name',
            field=models.CharField(default='article.html', max_length=50, verbose_name='Layout del articulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1, verbose_name='Estado'),
        ),
    ]
