# Generated by Django 3.0.6 on 2020-05-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0009_auto_20200519_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.URLField(blank=True, verbose_name='Fuente'),
        ),
    ]
