# Generated by Django 3.0.6 on 2020-05-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0010_auto_20200519_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bib',
            field=models.TextField(blank=True, verbose_name='Bibliografía'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
