# Generated by Django 3.0.6 on 2020-05-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0011_auto_20200519_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
