# Generated by Django 3.0.6 on 2020-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0012_auto_20200519_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='author',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Colegio'),
        ),
    ]
