# Generated by Django 3.0.6 on 2020-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0013_auto_20200522_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='me@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
