# Generated by Django 3.0.6 on 2020-05-26 15:19

from django.db import migrations, models
import revista.models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0014_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to=revista.models.Author.path, verbose_name='Foto'),
        ),
    ]
