# Generated by Django 3.0.6 on 2020-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0015_auto_20200526_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-update'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='image',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
    ]
