# Generated by Django 3.0.6 on 2020-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0016_auto_20200530_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='slug'),
        ),
    ]
