# Generated by Django 3.1.1 on 2020-09-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0018_auto_20200530_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número')),
                ('pub_date', models.DateField(verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Edición',
                'verbose_name_plural': 'Ediciones',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='claps',
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='revista.issue', verbose_name='Edición'),
        ),
    ]
