# Generated by Django 3.1.1 on 2020-09-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0019_auto_20200906_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Edición actual'),
        ),
    ]
