# Generated by Django 3.1.1 on 2020-11-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0020_issue_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date', '-update'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
    ]
